# friend:
#     path:     /
#     defaults: { _controller: "FTWBeerCountBundle:Friend:index" }

# friend_show:
#     path:     /{id}/show
#     defaults: { _controller: "FTWBeerCountBundle:Friend:show" }

# friend_new:
#     path:     /new
#     defaults: { _controller: "FTWBeerCountBundle:Friend:new" }

# friend_create:
#     path:     /create
#     defaults: { _controller: "FTWBeerCountBundle:Friend:create" }
#     requirements: { _method: post }

# friend_edit:
#     path:     /{id}/edit
#     defaults: { _controller: "FTWBeerCountBundle:Friend:edit" }

# friend_update:
#     path:     /{id}/update
#     defaults: { _controller: "FTWBeerCountBundle:Friend:update" }
#     requirements: { _method: post|put }

# friend_delete:
#     path:     /{id}/delete
#     defaults: { _controller: "FTWBeerCountBundle:Friend:delete" }
#     requirements: { _method: post|delete }
